### PR TITLE
Add support for priorityClass and containerSecurityContext #83

### PR DESCRIPTION
**Pull request by AshutoshNirkhe**

### CODE REVIEW

**Comment by AshutoshNirkhe** [comment]
@lwolf any plan on releasing next version of chart so that I can use these settings ?

**Comment by lwolf** [comment]
yes, will make a release over weekend

**Comment by AshutoshNirkhe** [comment]
> not really, apparently travis-ci ceased to exist, so I need to do a migration to github-actions. You can use chart directly from this repo if you "have to". I'll try to bump it manually in "lwolf-charts" without CI

I see. We are using terraform automation around that and currently fetching the chart from this upstream repo. Really appreciate if you could bump it without CI :)

**Comment by lwolf** [comment]
@AshutoshNirkhe do you fetch it from this repo (by getting tar.gz of the repo and then installing the chart) or do you use hosted charts - https://github.com/lwolf/kube-charts ?

**Comment by AshutoshNirkhe** [comment]
> @AshutoshNirkhe do you fetch it from this repo (by getting tar.gz of the repo and then installing the chart) or do you use hosted charts - https://github.com/lwolf/kube-charts ?

I am using helm_release terraform resource which in the end uses https://charts.lwolf.org to fetch the kube-cleanup chart.

**Comment by lwolf** [comment]
pushed the new version of the chart. Could you try it?

**Comment by AshutoshNirkhe** [comment]
> pushed the new version of the chart. Could you try it?

Will try it out and let you know more, thanks a lot.

**Comment by AshutoshNirkhe** [comment]
> pushed the new version of the chart. Could you try it?

@lwolf sorry to bother again, but I messed up the indentation in this PR. So opened https://github.com/lwolf/kube-cleanup-operator/pull/86 to fix just that. Off course one line change. Could you please re-build/push chart version 1.0.2 or create 1.0.3 ?

**Comment by lwolf** [comment]
pushed, try `kube-cleanup-operator-1.0.4`

**Pull request merged**
